### PR TITLE
Dataset Generation Module with Design Patterns

### PR DESCRIPTION
**Pull request by Shivesh777**
This pull request introduces a comprehensive dataset generation module for the Playground project. The module implements several design patterns, including Singleton, Strategy, and Composite, to provide a flexible and extensible solution for generating datasets used in the project.

#### Singleton Pattern

The Singleton pattern is employed to ensure that the dataset generators (`CircularDatasetGenerator`, `QuadrantDatasetGenerator`, `SpiralDatasetGenerator`, and `ClusterDatasetGenerator`) have a single global instance across the application. This guarantees that all dataset generation requests go through the same generator instances, promoting consistency and avoiding unnecessary instantiation.

#### Strategy Pattern

The Strategy pattern is used to enable dynamic switching between different dataset generation algorithms. The `DatasetGenerator` interface defines the contract for dataset generation algorithms, and individual generator classes implement this interface. The `DataProcessor` class acts as the client and accepts a dataset generator as a constructor parameter, allowing it to work with any class that implements the `DatasetGenerator` interface.

#### Composite Pattern

The Composite pattern is employed in the `TransformDatasets` class to transform the dataset from an ArrayList of ArrayLists to an ArrayList of Lists with weights. This transformation allows for more efficient data representation, where each point includes coordinates and associated weights. The Composite pattern enables the processing of complex nested data structures with a unified interface.

### Dataset Generation

With the integration of these design patterns, the dataset generation module offers a user-friendly approach to generate datasets. Users can utilize the `DataProcessor` class to generate datasets of different patterns, including circular clusters, quadrant datasets, spiral patterns, and clustered datasets.

The `DataProcessor` class acts as the main entry point to generate datasets. Simply create an instance of `DataProcessor` by passing the desired `DatasetGenerator` (e.g., `CircularDatasetGenerator`, `QuadrantDatasetGenerator`, etc.) as a parameter. Then, use the `process` method of `DataProcessor` to generate the dataset.

```java
// Example usage of DataProcessor to generate a circular dataset
DatasetGenerator circularDatasetGenerator = new CircularDatasetGenerator();
DataProcessor dataProcessor = new DataProcessor(circularDatasetGenerator);
ArrayList<ArrayList<Object>> generatedData = dataProcessor.process(10);
```

This pull request also includes extensive unit tests for each component, ensuring the correctness and reliability of the dataset generation module.

I believe this enhancement significantly improves the overall functionality and maintainability of the Playground project. The adoption of design patterns provides a robust foundation for future developments and extension of dataset generation capabilities.

Please review this pull request, and I welcome any feedback or suggestions for improvement.

Thank you.

### CODE REVIEW

**Comment by Shivesh777** [comment]
## Architecture Improvements with SOLID Principles and Code Abstraction

This pull request brings not only a comprehensive dataset generation module but also significant improvements in the overall architecture of the Playground project. The implementation adheres to SOLID principles (Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion) and promotes Code Abstraction (CA) to achieve a more maintainable, extensible, and organized codebase.

### SOLID Principles

#### Single Responsibility Principle (SRP)

The `DataProcessor` class adheres to the SRP by taking the responsibility of dataset generation away from the `FeatureController`. This separation of concerns makes the codebase cleaner and more focused on specific tasks, enhancing code readability and maintainability.

#### Open/Closed Principle (OCP)

The implementation of the Strategy pattern allows for the extension of dataset generation capabilities without modifying existing code. By introducing new classes that implement the `DatasetGenerator` interface, we can easily introduce additional dataset generation algorithms, ensuring the codebase remains open for extension but closed for modification.

#### Liskov Substitution Principle (LSP)

The `DatasetGenerator` interface acts as a contract, ensuring that all concrete generator classes (e.g., `CircularDatasetGenerator`, `QuadrantDatasetGenerator`, etc.) can be used interchangeably in the `DataProcessor`. This promotes robustness and makes it easier to add new generators in the future.

#### Interface Segregation Principle (ISP)

The `DatasetGenerator` interface is designed to have minimal and specific methods required for generating datasets. This ensures that the implementing classes do not have to implement unnecessary methods, promoting a more focused and concise design.

#### Dependency Inversion Principle (DIP)

The use of the `DatasetGenerator` interface in the `DataProcessor` class demonstrates adherence to DIP. Instead of depending on concrete classes directly, the `DataProcessor` relies on abstractions, which decouples the high-level module from low-level details, leading to a more flexible and maintainable architecture.

### Code Abstraction

The `DataProcessor` class acts as an abstraction layer, hiding the dataset generation details from the `FeatureController`. This abstraction allows the `FeatureController` to focus solely on applying features to the datasets without worrying about dataset generation logic. As a result, the `FeatureController` becomes more concise and easier to manage.

### Improved Architecture and Faster Feature Application

The adoption of design patterns, adherence to SOLID principles, and Code Abstraction significantly reduce the load on the `FeatureController`. As a result, features can be applied faster and with greater efficiency on the datasets, enhancing the overall performance of the Playground project.

Overall, these architectural improvements lead to a more organized, modular, and maintainable codebase. They provide a solid foundation for future enhancements and contribute to the overall robustness of the dataset generation module.

**Review by Rishit-dagli — APPROVED** [review]
Looks good to me /lgtm

**Review by Ford-Robert — CHANGES_REQUESTED** [review]
Very nice use of the Strategy Principal! Could we possibly use factory pattern to split off the getData logic to better adhere to the SRP. But it is important that createTrainingData is unaffected by any changes.

**Review by Rishit-dagli — APPROVED** [review]

**Review by Ford-Robert — COMMENTED** [review]
lgtm!

**Review by Ford-Robert — APPROVED** [review]
lgtm!

**Pull request merged**
