### PR TITLE
Documentation for Network Training code

### PR DESCRIPTION
**Pull request by Rishit-dagli**
This adds JavaDocs for the model training code.

### CODE REVIEW

**Review by Ford-Robert — APPROVED** [review]
Looks great! Very descriptive, excellent job!

**Review by Shivesh777 — DISMISSED** [review]

**Review by Shivesh777 — APPROVED** [review]

**Review by Shivesh777 — APPROVED** [review]

**Comment by Rishit-dagli** [comment]
SInce there were new commits pushed

/cc Ford-Robert

**Review by Ford-Robert — APPROVED** [review]
lgtm!

**Pull request merged**
