### PR TITLE
Create CONSTANTS for feature strings

### PR DESCRIPTION
**Pull request by Ford-Robert**
In this pull request, I introduced a new class `FeatureConstants` that houses the feature name strings used across several classes. By refactoring these strings into constants, we have made the code more robust, less error-prone, and consistent with clean architecture principles. By removing hardcoded strings that were repeated across multiple files, we've eliminated the code smell associated with duplication. Any future changes to the feature names can be done in one place, thereby making the codebase more maintainable. It ensures that the code is more modular and adheres to the "Don't Repeat Yourself" (DRY) principle.

### CODE REVIEW

**Comment by Rishit-dagli** [comment]
@snkrs23 @alvina-yang @T3CHW1ZRD are we using these same constant strings to display the text on the UI?

**Review by Shivesh777 — CHANGES_REQUESTED** [review]
@Ford-Robert do you also need to update your tests to match this implementation?

**Comment by Ford-Robert** [comment]
> @Ford-Robert do you also need to update your tests to match this implementation?
Yes I will create another PR, with my full testing suite


> @snkrs23 @alvina-yang @T3CHW1ZRD are we using these same constant strings to display the text on the UI?
I believe I changed all references to these string on the UI end, but I am not sure about that

**Comment by snkrs23** [comment]
> @snkrs23 @alvina-yang @T3CHW1ZRD are we using these same constant strings to display the text on the UI?

No, we didn't.

**Review by Shivesh777 — APPROVED** [review]

**Comment by Rishit-dagli** [comment]
> No, we didn't.

@snkrs23 We should

**Review by Rishit-dagli — APPROVED** [review]
Just the merge conflicts need to be fixed

**Pull request merged**
