### PR TITLE
Create Controller Tests

### PR DESCRIPTION
**Pull request by snkrs23**
This pull requests implements two classes, namely  `DataAttributesControllerTest` and `MlParametersControllerTest`, which test their respectively named controllers. 

- Each test in the implemented classes can be ran individually if desired. 

This pull request serves to extend coverage of classes throughout the application,

### CODE REVIEW

**Review by Rishit-dagli — CHANGES_REQUESTED** [review]
Aren't all the controllers interface adapaters? Why do we change that bit?

**Comment by Rishit-dagli** [comment]
DOes this follow #88? or does this supersede #88?

**Review by T3CHW1ZRD — APPROVED** [review]

**Comment by snkrs23** [comment]
> Aren't all the controllers interface adapaters? Why do we change that bit?

This is to avoid dependency issues.

**Review by alvina-yang — APPROVED** [review]

**Comment by snkrs23** [comment]
> DOes this follow #88? or does this supersede #88?

Supercede.

**Comment by Rishit-dagli** [comment]
> Conforms to the plan of solving dependency issues.

@snkrs23 Could you elaborate how this solves that?

**Comment by snkrs23** [comment]
> > Conforms to the plan of solving dependency issues.
> 
> @snkrs23 Could you elaborate how this solves that?

There was a dependency issue with the controllers and `fxml` files pointed out by our TA after the presentation to Alvina.

**Comment by Rishit-dagli** [comment]
> There was a dependency issue with the controllers and fxml files pointed out by our TA after the presentation to Alvina.

Sorry what was the issue and how does placing something which is a controller outside a controller fix that?

**Comment by snkrs23** [comment]
> > There was a dependency issue with the controllers and fxml files pointed out by our TA after the presentation to Alvina.
> 
> Sorry what was the issue and how does placing something which is a controller outside a controller fix that?

It is a controller test located in the controller folder. It is not a controller itself. Please review the names of the commited files.

**Comment by Rishit-dagli** [comment]
What my now stale review commented on was the the controller classes which were put in a folder outside interface adapter

**Comment by Rishit-dagli** [comment]
So I wanted to ask how putting classes which are interface adapter outside interface adapters fix the issue?

**Comment by snkrs23** [comment]
> So I wanted to ask how putting classes which are interface adapter outside interface adapters fix the issue?

They are tests not interface adapters, also please review #94 about that as well.

**Comment by Rishit-dagli** [comment]
How is `src/main/java/com/playground/playground/controller/DataAttributesController.java` a test?

**Pull request merged**
