### PR TITLE
JUnit tests in Dataset Generation

### PR DESCRIPTION
**Pull request by Shivesh777**
Modified tests to follow JUnit style guide for dataset generation.

### CODE REVIEW

**Comment by Shivesh777** [comment]
@Rishit-dagli could you help me pass the gradle checks here, it is implemented the same way you did on your PR, it works locally but does not pass the checks here?

**Comment by Rishit-dagli** [comment]
@Shivesh777 yes because the build.gradle for your base is not modified like what I did

**Comment by Rishit-dagli** [comment]
at the moment let me change the base to my branch which will let us check if the workflows work and then we will later change the base and merge it to main

**Comment by Rishit-dagli** [comment]
The tests should now pass but please don't merge without changing base, we will have way too many merge conflicts

**Comment by Rishit-dagli** [comment]
Hmm... this is interesting, let me change the base back to main but merge #53 into this, and then you could wait until #53 is merged to merge this PR

**Review by Rishit-dagli — APPROVED** [review]
/lgtm

**Pull request closed without merging**
