### PR TITLE
Add tests for dataset generator classes

### PR DESCRIPTION
**Pull request by Shivesh777**
## Pull Request Description

This PR aims to achieve 100% test coverage for the data-related components within the Playground project. The implemented unit tests comprehensively cover various dataset generators and data processing functionalities. By enhancing test coverage, we ensure that the code behaves consistently and mitigate the risk of potential regressions.

### Changes Made

- Introduced tests for key dataset generators: `CircularDatasetGenerator`, `QuadrantDatasetGenerator`, `SpiralDatasetGenerator`, and `ClusterDatasetGenerator`.
- Verified the generation of valid and non-empty datasets by each dataset generator.
- Tested the correctness of data transformation through `TransformDatasets`.
- Validated data processing using `DataProcessor` to confirm accurate transformation.
- Enriched test coverage throughout the entire data package.

### Checklist

- [x] Added tests to comprehensively cover data-related functionalities.
- [x] Confirmed successful test execution and achieved 100% coverage.
- [x] Ensured the PR description offers a clear overview of the implemented changes.
- [x] Verified that the code adheres to the project's coding standards and guidelines.

### CODE REVIEW

**Review by Ford-Robert — APPROVED** [review]
Great addition to complete a comprehensive testing suite!

**Comment by Rishit-dagli** [comment]
/retitle Add tests for dataset generator classes

**Review by Rishit-dagli — APPROVED** [review]
/lgtm

**Pull request merged**
