### PR TITLE
Remove Unused JavaFX elements for discretize, regenerate, test data, and step button

### PR DESCRIPTION
**Pull request by snkrs23**
This pull request removes unused JavaFX components from the user interface (i.e. `regenerate` button , `stepButton` button, `showTestData` check box, and `discreteOutput` checkbox). Labels were also added below the ML parameter menu bar that display the user's current selection.

### CODE REVIEW

**Review by alvina-yang — APPROVED** [review]
Everything looks great! Thanks for removing all the buttons which weren't needed.

**Comment by Rishit-dagli** [comment]
/retitle Remove Unused JavaFX elements for discretize, regenerate, test data, and step button

**Review by Rishit-dagli — APPROVED** [review]
/approve

**Review by Rishit-dagli — COMMENTED** [review]
Do we reference interface adapter code elsewhere in the codebase, if so we will need to change those references too?

**Review by Shivesh777 — APPROVED** [review]

**Pull request merged**
