### PR TITLE
User Interface

### PR DESCRIPTION
**Pull request by snkrs23**
Contains all the files corresponding to the Graph System, Data Attributes, Features, Hidden Layers, and ML Parameters. Note that before, we attempted to separate the aforementioned features into 4 different pull requests but each would fail the autograde as the files are dependent on each other.

### CODE REVIEW

**Comment by alvina-yang** [comment]
Already reviewed the code previously (on another pr), good to merge.

**Review by alvina-yang — APPROVED** [review]

**Comment by Rishit-dagli** [comment]
I left comments on #29 and #33, couyld you resolve those

**Pull request merged**
